import { Inter } from "next/font/google";
import "./globals.css";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My first Web React",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <link rel="stylesheet" href="global.css"></link>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
